# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cat Grouping Coding Exercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cat Grouping Coding Exercise
  pod 'ReactiveSwift', '~> 3.0'
  pod 'ReactiveCocoa', '~> 7.0'

  target 'Cat Grouping Coding ExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
